# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4WwbAVIOIz3M4U-Ex6HskZbIeJO7e4y
"""

Students={"id":[], "name":[], "dob":[]}
Courses={"id":[], "name":[]}
Marks=[]

def getS():
  n=int(input("Number of students: "))
  return n

def getC():
  n=int(input("Number of courses: "))
  return n

def getStdInfo(n):
  for i in range (0,n):
    print("Student ",i+1)
    Students["id"].append(input("ID "))
    Students["name"].append(input("Name "))
    Students["dob"].append(input("DOB "))

def getCrsInfo(n):
  for i in range(0,n):
    print("Course ",i+1)
    Courses["id"].append(input("ID "))
    Courses["name"].append(input("Name "))

def listStudent(n):
  for i in range (0,n):
    print(f"""Student {i+1}:
      ID - {Students["id"][i]}
      Name - {Students["name"][i]}
      DOB - {Students["dob"][i]}
    ---------------------------""")

def listCourses(n):
  for i in range (0,n):
    print(f"""Course {i+1}:
      ID - {Courses["id"][i]}
      Name - {Courses["name"][i]}
    ---------------------------""")

def getMarks(name, n):
  print(f"\nEnter the marks of course {name}:")
  for i in range(0,n):
    Marks.append(input(f"{Students["name"][i]}: "))

def showMarks(name,n):
  print(f"Marks of course {name}:")
  for i in range(0,n):
    print(f"Student {Students["name"][i]} - {Marks[i]}")

def findCrs(id,n):
  for i in range (0,n):
    if (Courses["id"][i]==id):
      return Courses["name"][i]
  print("Not Exist")
  return -1


ns=getS()
getStdInfo(ns)

nc=getC()
getCrsInfo(nc)

#select a course
idc=input("Enter the ID of course selected: ")
cn=findCrs(idc,nc)    #neu tim thay name course or not -1
if (cn!=-1):
  getMarks(cn,ns)

print("======================================LIST=====================")
listStudent(ns)
listCourses(nc)
#print(f"Students Info: {Students}")
#print(f"Courses Info: {Courses}")

if (cn!=-1):
  showMarks(cn,ns)